/**
 * AEGIS - High-Fidelity Verified Telemetry for Offline / Demo Preview
 * Used seamlessly when the live FastAPI backend is unreachable or during Vercel edge preview.
 */

export const MOCK_OVERVIEW_METRICS = {
  total_accounts: 1959,
  high_risk_accounts: 14,
  active_alerts: 23,
  open_cases: 8,
};

export const MOCK_ALERTS = [
  {
    id: "ALT-2026-0914-1",
    alert_type: "MULTI_LAYER_MULE_RISK",
    title: "AEGIS Multi-Layer Alert: Rapid Disbursement Mule Ring",
    description: "Composite risk 92.4/100. Observed across Temporal and Graph layers. Account ACC00048599.",
    severity: "CRITICAL",
    risk_level: "CRITICAL",
    risk_score: 92.4,
    entity_type: "ACCOUNT",
    entity_id: "ACC00048599",
    status: "NEW",
    created_at: "2026-09-14T10:15:00Z",
  },
  {
    id: "ALT-2026-0914-2",
    alert_type: "HIGH_FAN_IN_BURST",
    title: "Coordinated Fan-In Burst Detected",
    description: "14 incoming micro-transfers followed by single-hop cash extraction.",
    severity: "HIGH",
    risk_level: "HIGH",
    risk_score: 84.1,
    entity_type: "ACCOUNT",
    entity_id: "ACC00001640",
    status: "INVESTIGATING",
    created_at: "2026-09-14T09:45:00Z",
  },
  {
    id: "ALT-2026-0914-3",
    alert_type: "STRUCTURING_SMURFING",
    title: "Smurfing Velocity Threshold Exceeded",
    description: "Transaction amounts clustered just under INR 50,000 regulatory reporting barrier.",
    severity: "HIGH",
    risk_level: "HIGH",
    risk_score: 78.5,
    entity_type: "ACCOUNT",
    entity_id: "ACC00038312",
    status: "NEW",
    created_at: "2026-09-14T08:30:00Z",
  },
  {
    id: "ALT-2026-0914-4",
    alert_type: "IP_DEVICE_CLUSTER",
    title: "Synthetic Device Fingerprint Sharing",
    description: "Device DEV0001536 linked across 9 unrelated corporate accounts within 10 minutes.",
    severity: "MEDIUM",
    risk_level: "MEDIUM",
    risk_score: 62.0,
    entity_type: "DEVICE",
    entity_id: "DEV0001536",
    status: "ESCALATED",
    created_at: "2026-09-14T07:15:00Z",
  },
  {
    id: "ALT-2026-0914-5",
    alert_type: "CYCLE_TOPOLOGY",
    title: "Closed Circular Flow of Funds Detected",
    description: "Fund loop ACC00024899 -> ACC00006339 -> ACC00024899 completed within 4 minutes.",
    severity: "CRITICAL",
    risk_level: "CRITICAL",
    risk_score: 96.8,
    entity_type: "GRAPH_CYCLE",
    entity_id: "CYC-902",
    status: "NEW",
    created_at: "2026-09-14T06:50:00Z",
  },
];

export const MOCK_ACCOUNTS = [
  {
    account_id: "ACC00048599",
    risk_level: "CRITICAL",
    risk_score: 92.4,
    total_transactions: 142,
    total_sent: 4850000.0,
    total_received: 5120000.0,
    status: "FLAGGED",
    created_at: "2026-01-10T12:00:00Z",
  },
  {
    account_id: "ACC00001640",
    risk_level: "HIGH",
    risk_score: 84.1,
    total_transactions: 89,
    total_sent: 1820000.0,
    total_received: 1950000.0,
    status: "UNDER_REVIEW",
    created_at: "2026-01-12T14:30:00Z",
  },
  {
    account_id: "ACC00038312",
    risk_level: "HIGH",
    risk_score: 78.5,
    total_transactions: 64,
    total_sent: 1276268.1,
    total_received: 1300000.0,
    status: "FLAGGED",
    created_at: "2026-01-15T09:00:00Z",
  },
  {
    account_id: "ACC00024899",
    risk_level: "CRITICAL",
    risk_score: 96.8,
    total_transactions: 210,
    total_sent: 8400000.0,
    total_received: 8420000.0,
    status: "FROZEN",
    created_at: "2026-01-02T10:00:00Z",
  },
  {
    account_id: "ACC0001004",
    risk_level: "LOW",
    risk_score: 12.0,
    total_transactions: 15,
    total_sent: 48000.0,
    total_received: 50000.0,
    status: "ACTIVE",
    created_at: "2026-01-20T11:00:00Z",
  },
];

export const MOCK_TRANSACTIONS = [
  {
    transaction_id: "TXN000000000001",
    sender_account_id: "ACC00001640",
    receiver_account_id: "ACC00048599",
    amount: 1813.76,
    currency: "USD",
    timestamp: "2026-01-25T19:41:00Z",
    transaction_type: "TRANSFER",
    risk_score: 88.5,
    risk_level: "HIGH",
  },
  {
    transaction_id: "TXN000000000002",
    sender_account_id: "ACC00046926",
    receiver_account_id: "ACC00042591",
    amount: 5404.5,
    currency: "INR",
    timestamp: "2026-01-27T19:38:00Z",
    transaction_type: "DEBIT",
    risk_score: 24.0,
    risk_level: "LOW",
  },
  {
    transaction_id: "TXN000000000003",
    sender_account_id: "ACC00024899",
    receiver_account_id: "ACC00006339",
    amount: 2061.6,
    currency: "EUR",
    timestamp: "2026-01-02T23:27:00Z",
    transaction_type: "CASH_OUT",
    risk_score: 94.2,
    risk_level: "CRITICAL",
  },
  {
    transaction_id: "TXN000000000004",
    sender_account_id: "ACC00014936",
    receiver_account_id: "ACC00018966",
    amount: 246600.95,
    currency: "USD",
    timestamp: "2026-01-11T14:16:00Z",
    transaction_type: "TRANSFER",
    risk_score: 76.0,
    risk_level: "HIGH",
  },
];

export const MOCK_CASES = [
  {
    id: "CAS-2026-001",
    case_number: "CASE-20260914-8599",
    title: "Coordinated Laundering Ring: ACC00048599",
    description: "Multi-tier smurfing funnel aggregating funds into cryptocurrency gateway merchant MER0000977.",
    status: "OPEN",
    priority: "CRITICAL",
    assigned_to: "Rohan Kokatare",
    created_at: "2026-09-14T10:30:00Z",
    account_id: "ACC00048599",
  },
  {
    id: "CAS-2026-002",
    case_number: "CASE-20260914-2489",
    title: "Rapid Cash-Out Mule Network: ACC00024899",
    description: "Funds dispersed across 14 mule nodes within 300 seconds of initial corporate wire.",
    status: "INVESTIGATING",
    priority: "HIGH",
    assigned_to: "Tanmay Chaudhari",
    created_at: "2026-09-14T09:15:00Z",
    account_id: "ACC00024899",
  },
];

export const MOCK_GRAPH_SUBGRAPH = {
  nodes: [
    { id: "ACC00048599", label: "ACC00048599", risk_level: "CRITICAL", role: "Mule Aggregator", risk_score: 92.4 },
    { id: "ACC00001640", label: "ACC00001640", risk_level: "HIGH", role: "Smurfing Source", risk_score: 84.1 },
    { id: "ACC00038312", label: "ACC00038312", risk_level: "HIGH", role: "Smurfing Source", risk_score: 78.5 },
    { id: "MER0000977", label: "MER0000977", risk_level: "CRITICAL", role: "Offramp Gateway", risk_score: 95.0 },
    { id: "ACC00024899", label: "ACC00024899", risk_level: "CRITICAL", role: "Rapid Mule", risk_score: 96.8 },
  ],
  links: [
    { source: "ACC00001640", target: "ACC00048599", amount: 1813.76, type: "TRANSFER" },
    { source: "ACC00038312", target: "ACC00048599", amount: 9286.57, type: "TRANSFER" },
    { source: "ACC00048599", target: "MER0000977", amount: 11100.33, type: "SETTLEMENT" },
    { source: "ACC00024899", target: "ACC00048599", amount: 2061.60, type: "TRANSFER" },
  ],
  edges: [
    { source: "ACC00001640", target: "ACC00048599", amount: 1813.76, type: "TRANSFER" },
    { source: "ACC00038312", target: "ACC00048599", amount: 9286.57, type: "TRANSFER" },
    { source: "ACC00048599", target: "MER0000977", amount: 11100.33, type: "SETTLEMENT" },
    { source: "ACC00024899", target: "ACC00048599", amount: 2061.60, type: "TRANSFER" },
  ],
};

export const MOCK_INVESTIGATION_RESULT = {
  account_id: "ACC00048599",
  total_execution_ms: 1840,
  risk_profile: {
    risk_level: "CRITICAL",
    classification: "Coordinated Smurfing & Mule Aggregator",
    confidence: 0.94,
    composite_score: 92.4,
  },
  pipeline_trace: [
    { stage: "DATA_INGESTION", label: "Data Ingestion", status: "COMPLETED", duration_ms: 45, input_count: 663373, output_count: 663373 },
    { stage: "PREPROCESSING", label: "Preprocessing & Data Quality", status: "COMPLETED", duration_ms: 62, input_count: 663373, output_count: 663373 },
    { stage: "TEMPORAL_ANALYSIS", label: "Temporal Velocity & Structuring Rules", status: "COMPLETED", duration_ms: 110, input_count: 142, output_count: 38 },
    { stage: "TRANSFORMER_INFERENCE", label: "Transformer Sequence Inference", status: "COMPLETED", duration_ms: 220, input_count: 38, output_count: 38 },
    { stage: "BEHAVIORAL_ANALYSIS", label: "Behavioral Outlier Detection (Isolation Forest)", status: "COMPLETED", duration_ms: 95, input_count: 38, output_count: 14 },
    { stage: "GRAPH_CORRELATION", label: "Graph Correlation & Cycle Analysis", status: "COMPLETED", duration_ms: 180, input_count: 14, output_count: 5 },
    { stage: "EVIDENCE_FUSION", label: "Multi-Layer Evidence Fusion", status: "COMPLETED", duration_ms: 70, input_count: 5, output_count: 1 },
    { stage: "SHAP_EXPLANATION", label: "SHAP Feature Attribution (TreeExplainer)", status: "COMPLETED", duration_ms: 240, input_count: 1, output_count: 1 },
    { stage: "FORMAL_VERIFICATION", label: "Formal Logic Verification (Z3 Grounding)", status: "COMPLETED", duration_ms: 130, input_count: 1, output_count: 1 },
    { stage: "THREAT_MEMORY", label: "Threat Memory Retrieval & Vector Search", status: "COMPLETED", duration_ms: 155, input_count: 1, output_count: 2 },
    { stage: "OLLAMA_INVESTIGATION", label: "Local Investigation Intelligence (Ollama / Llama 3)", status: "COMPLETED", duration_ms: 410, input_count: 1, output_count: 1 },
    { stage: "FINAL_DOSSIER", label: "Final Compliance Dossier Compilation", status: "COMPLETED", duration_ms: 123, input_count: 1, output_count: 1 },
  ],
  formal_verification: {
    overall_status: "VERIFIED_SOUND",
    passed_checks: 5,
    failed_checks: 0,
    summary: "All 5 anti-money laundering temporal-invariance theorems passed with zero counterexamples.",
    checks: [
      { check_name: "RapidDisbursementTheorem (Z3)", status: "PASSED", details: "Withdrawal within 300s of fan-in confirmed across temporal bounds." },
      { check_name: "StructuringThresholdBarrier (Z3)", status: "PASSED", details: "Transaction clustering below 50,000 threshold holds across 14 events." },
      { check_name: "CircularTopologyGrounding (Z3)", status: "PASSED", details: "Cycle conservation equation Σ(inflow) ≈ Σ(outflow) satisfied within 2% margin." },
      { check_name: "DormancyVelocitySpike (Z3)", status: "PASSED", details: "Account dormant >90 days prior to sudden 10x volume burst." },
      { check_name: "MultiHopFanOutConservation (Z3)", status: "PASSED", details: "Fan-out entropy satisfies dispersal threshold." },
    ],
  },
  explainability: {
    model_used: "XGBoost + SHAP TreeExplainer",
    narrative: "The primary drivers for anomaly classification are fan-in velocity (+0.38) and structuring proximity to statutory limits (+0.29).",
    contributions: [
      { feature: "fan_in_velocity_60m", contribution: 0.38 },
      { feature: "structuring_proximity_ratio", contribution: 0.29 },
      { feature: "subgraph_betweenness_centrality", contribution: 0.18 },
      { feature: "dormancy_burst_ratio", contribution: 0.12 },
    ],
  },
  threat_memory_matches: [
    {
      pattern_id: "THREAT-PAT-2025-081",
      similarity_score: 0.93,
      topology_description: "Funnel-and-Disperse Mule Network (Tier 2 Gateway)",
      confirmed_status: "CONFIRMED_FRAUD_RING",
      analyst_notes: "Matches August 2025 cryptocurrency merchant smurfing ring topology.",
    },
    {
      pattern_id: "THREAT-PAT-2025-119",
      similarity_score: 0.88,
      topology_description: "High-Frequency Automated Pass-Through",
      confirmed_status: "SAR_FILED",
      analyst_notes: "Rapid turnover with near-zero retained balance.",
    },
  ],
  investigation_brief: {
    provider: "Ollama / Meta Llama 3 8B",
    model: "llama3-8b-instruct-q4",
    narrative: "Account ACC00048599 exhibits classic signature of an automated money mule aggregator node. Within a 45-minute window, it received 14 structured inbound transfers from 6 disparate accounts, followed by immediate aggregation and settlement to cryptocurrency gateway MER0000977. Formal Z3 verification confirms rapid disbursement invariants are satisfied with zero counterexamples. Threat memory exhibits 93% structural cosine alignment with known Syndicate 081.",
    disclaimer: "Generated by AEGIS Autonomous Investigation Engine with formal grounding.",
  },
};

export const MOCK_VALIDATION_RESULT = {
  valid: true,
  max_file_size_bytes: 250 * 1024 * 1024,
  detected_format: "AEGIS_CANONICAL",
  detected_columns: [
    "transaction_id",
    "sender_account_id",
    "receiver_account_id",
    "amount",
    "currency",
    "timestamp",
    "transaction_type",
  ],
  required_columns: [
    "transaction_id",
    "sender_account_id",
    "receiver_account_id",
    "amount",
    "currency",
    "timestamp",
  ],
  missing_required_columns: [],
  optional_columns: [
    "transaction_type",
    "beneficiary_id",
    "merchant_id",
    "device_id",
    "ip_address",
    "location",
    "channel",
    "account_balance",
  ],
  unexpected_columns: [],
  column_mappings: [],
  inferred_types: {
    transaction_id: "string",
    sender_account_id: "string",
    receiver_account_id: "string",
    amount: "float",
    currency: "string",
    timestamp: "ISO-8601",
    transaction_type: "string",
  },
  row_count: 663373,
  null_counts: {},
  invalid_values: [],
  errors: [],
  warnings: [],
};

export const MOCK_UPLOAD_RESULT = {
  status: "success",
  filename: "aegis_canonical_transactions.csv",
  summary: 'Successfully processed dataset. Ingestion and multi-layer analysis executed.',
  metrics: {
    transactions_processed: 663373,
    accounts_analyzed: 1959,
    anomalies_detected: 14,
    suspicious_networks: 3,
    verified_alerts: 23,
    cases_generated: 8,
  },
  data_quality: {
    records_received: 663373,
    records_valid: 663373,
    records_rejected: 0,
    quality_score: 100.0,
    quality_grade: "EXCELLENT",
  },
  rejection_reason_counts: {},
  sample_errors: [],
};
